# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kenan/Desktop/PW_DevTech

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kenan/Desktop/PW_DevTech/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kenan/Desktop/PW_DevTech/build/CMakeFiles /home/kenan/Desktop/PW_DevTech/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kenan/Desktop/PW_DevTech/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pro

# Build rule for target.
pro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pro
.PHONY : pro

# fast build rule for target.
pro/fast:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/build
.PHONY : pro/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/main.c.s
.PHONY : main.c.s

string_compare.o: string_compare.c.o

.PHONY : string_compare.o

# target to build an object file
string_compare.c.o:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/string_compare.c.o
.PHONY : string_compare.c.o

string_compare.i: string_compare.c.i

.PHONY : string_compare.i

# target to preprocess a source file
string_compare.c.i:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/string_compare.c.i
.PHONY : string_compare.c.i

string_compare.s: string_compare.c.s

.PHONY : string_compare.s

# target to generate assembly for a file
string_compare.c.s:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/string_compare.c.s
.PHONY : string_compare.c.s

string_length.o: string_length.c.o

.PHONY : string_length.o

# target to build an object file
string_length.c.o:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/string_length.c.o
.PHONY : string_length.c.o

string_length.i: string_length.c.i

.PHONY : string_length.i

# target to preprocess a source file
string_length.c.i:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/string_length.c.i
.PHONY : string_length.c.i

string_length.s: string_length.c.s

.PHONY : string_length.s

# target to generate assembly for a file
string_length.c.s:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/string_length.c.s
.PHONY : string_length.c.s

string_palindrome.o: string_palindrome.c.o

.PHONY : string_palindrome.o

# target to build an object file
string_palindrome.c.o:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/string_palindrome.c.o
.PHONY : string_palindrome.c.o

string_palindrome.i: string_palindrome.c.i

.PHONY : string_palindrome.i

# target to preprocess a source file
string_palindrome.c.i:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/string_palindrome.c.i
.PHONY : string_palindrome.c.i

string_palindrome.s: string_palindrome.c.s

.PHONY : string_palindrome.s

# target to generate assembly for a file
string_palindrome.c.s:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/string_palindrome.c.s
.PHONY : string_palindrome.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... pro"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... string_compare.o"
	@echo "... string_compare.i"
	@echo "... string_compare.s"
	@echo "... string_length.o"
	@echo "... string_length.i"
	@echo "... string_length.s"
	@echo "... string_palindrome.o"
	@echo "... string_palindrome.i"
	@echo "... string_palindrome.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

